# Commands executed for player on login. This placeholders are supported:
# {player} - name of player
onJoin:
  -
    delay: 100
    as: CONSOLE
    cmd: give {player} cookie 1
onFirstJoin:
  -
    delay: 100
    as: CONSOLE
    cmd: give {player} cookie 1
# Commands executed when player click on block, use type of -1 to ignore type.
# Players with 'core.oninteract.bypass' permission will be ignored.
onInteract:
  -
    material: CRAFTING_TABLE
    type: -1
    cancelAction: true
    delayedCommands:
      -
        delay: 0
        as: CONSOLE
        cmd: give {player} cookie 1

removeBoatOnExit: true
bungee: true
bungee_id: server