name: RiseCore
author: Travja
version: 1.0
description: The new and improved Core plugin for DarkRise
main: me.travja.darkrise.core.Core
api-version: 1.13
softdepend:
  - Vault
commands:
  corereload:
    description: Reloads RiseCore
    default: op
  stuck:
    description: Find yourself in a pickle? Use /<command> to get out.
    default: true